### ISSUE TITLE
parametrize auto.create.topics.enable

### ISSUE THREAD

**Issue by drummerwolli** [zalando/saiki-buku#11]
see https://kafka.apache.org/08/configuration.html

auto.create.topics.enable can be different for several environments or usecases ... we should make this parametrized in buku

**Comment by chutium** [comment]
this could be handled by ```create_broker_properties``` function: https://github.com/zalando/saiki-buku/commit/9244fd840e5fdd028623f874975bda69571b62c7#diff-c472c689e0e51bbbf9cbe79af8ff705eR22

currently we use a lot of default settings from official doc http://kafka.apache.org/documentation.html#prodconfig, we could think about parameterizing them or part of them, or maybe put config file on s3 and set s3 file path as parameter.

**Comment by drummerwolli** [comment]
i would be fine probably with https://github.com/zalando/saiki-buku/issues/14 making this not needed anymore, what do you think?

**Comment by chutium** [comment]
http endpoint will be fine, if later we have some private settings, we can change it to a s3 location
