### ISSUE TITLE
taking zookeeper prefix into account only works for stacks

### ISSUE THREAD

**Issue by JonasJurczok** [zalando/saiki-buku#27]
Hi,

in https://github.com/zalando/saiki-buku/blob/master/generate_zk_conn_str.py#L28 you are adding the prefix to the ip generated before. But apparently this only works for the last entry in the list. What happens if you actually have more than one ip.

I'm not that familiar with the ec2 api yet but it looks like you are actually adding all private IPs from all instances in the exhibitor LB. And then adding the prefix just to the last one seems wrong to me.

**Comment by chutium** [comment]
did you really get some issue with this? according to kafka's official document, this zk conn str we generated is totally right.

https://kafka.apache.org/documentation.html
https://kafka.apache.org/08/configuration.html

search the term "chroot"

you will see the format is:
```hostname1:port1,hostname2:port2,hostname3:port3/chroot/path```

Thanks for reviewing the code anyway.

**Comment by JonasJurczok** [comment]
Ah okay, thanks.
The only thing I'm seeing at the moment is that the system is waiting for zookeeper so I wasn't sure.

**Comment by chutium** [comment]
waiting for zk and never finished? during rebalance_partitions or?

**Comment by JonasJurczok** [comment]
No the Problem was that I did not configure the chroot in zookeeper. So
totally my fault :)
Am 28.01.2016 6:05 nachm. schrieb "Teng Qiu" <notifications@github.com>:
