### ISSUE TITLE
check for new ZK nodes

### ISSUE THREAD

**Issue by drummerwolli** [zalando/saiki-buku#30]
when a zk node dies and a new one starts on AWS, buku does not recognize this and still keeps the old ZK connection string. We should check for new nodes periodically and update the ENV variable, or even more ....

**Comment by chutium** [comment]
zk conn str should be checked every 60sec, done by this commit https://github.com/zalando/saiki-buku/blob/9244fd840e5fdd028623f874975bda69571b62c7/start_kafka_and_reassign_partitions.py#L50-L52

should still work, if we still use generate_zk_conn_str.py

**Comment by drummerwolli** [comment]
continued in https://github.com/zalando/saiki-buku/issues/34
